# Stage 1: Build stage
# Use an official Node.js runtime as the base image
FROM node:20.5.1-alpine AS build

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the app source code to the working directory
COPY . .

# Build the Next.js app
RUN npm run build

# Stage 2: Run stage
# Use a smaller base image for running the app
FROM node:20.5.1-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the built app from the previous build stage
COPY --from=build /usr/src/app .

# Specify the command to run the app
CMD ["npm", "run", "start"]