GET http://localhost:5000/api/v1/questions

###

POST http://localhost:5000/api/v1/questions
Content-Type: application/json

{
    "title": "Reverse a String",
    "categories": ["Strings", "Algorithms"],
    "complexity": "easy",
    "description": "Write a function that reverses a string. The input string is given as an array of characters s.",
    "link": "https://leetcode.com/problems/reverse-string/"
}

###
PATCH http://localhost:5000/api/v1/questions/65008e4a2d141f07160daa0f
Content-Type: application/json

{
    "complexity": "medium"
}

###

DELETE http://localhost:5000/api/v1/questions/650096e3701587aa79d06ae2