name: amplify

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ap-southeast-1
            AWS_DEFAULT_OUTPUT: json
        steps:
            - uses: actions/checkout@v2
            - name: Deploy
              run: ./scripts/amplify-deploy.sh xxxxxxxxxxxxx owen/question-service
