name: Using Cypress GH Action

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    single-run:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Create env file
              run: |
                  echo "${{secrets.ENV}}" >> Frontend/.env
            - name: Cypress run
              uses: cypress-io/github-action@v6
              timeout-minutes: 5
              with:
                  working-directory: Frontend
                  build: npm run build
                  start: npm start
                  browser: chrome
