name: Using Cypress GH Action

on: [push]

jobs:
    single-run:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Cypress run
              uses: cypress-io/github-action@v6
              timeout-minutes: 10
              with:
                  working-directory: Frontend
                  build: npm run build
                  start: npm start
